added tests to ci

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -24,5 +24,21 @@ jobs:
           ruby-version: 2.7
       - run: git clone git@github.com:QuickPay/klarna-payments-backend.git
       - run: gem install bundler
+      - run: cat .rubocop
+      - run: |1
+          assert_eq(){
+            exp="$1"
+            shift
+            act="$*"
+            if [[ "$act" == *"$exp"* ]]; then
+              echo "+1"
+            else
+              echo "failed test"
+              exit 1
+            fi
+          }
+      - name: Test connection to postgres server
+        run: assert_eq "test" $(psql -d postgresql://backends_u:abc@localhost/backends_test -c "select 'test';")
+      - name: Test pgcrypto is installed
+        run: psql -S -d postgresql://backends_u:abc@localhost/backends_test -c "select gen_random_uuid();"
       - run: cd klarna-payments-backend && bundle install
-      - run: ls -a
